"""Provider scaffold for JEPA WMS.

Generated by ``scripts/scaffold_provider.py``. Keep public capabilities disabled until
the TODO methods return validated WorldForge models and have fixture-driven tests.
"""

from __future__ import annotations

import os
from collections.abc import Callable
from time import perf_counter

from worldforge.models import (
    ActionScoreResult,
    JSONDict,
    ProviderCapabilities,
    ProviderEvent,
    ProviderHealth,
)

from .base import BaseProvider, ProviderError

JEPA_WMS_ENV_VAR = "JEPA_WMS_MODEL_PATH"


class JEPAWMSProvider(BaseProvider):
    """Generated scaffold for the JEPA WMS provider.

    Planned capabilities are intentionally not advertised yet. Enable them
    only after the corresponding methods call the real upstream runtime
    and return validated public models.
    """

    planned_capabilities = ("score",)
    taxonomy_category = "JEPA latent predictive world model"

    def __init__(
        self,
        name: str = "jepa-wms",
        *,
        event_handler: Callable[[ProviderEvent], None] | None = None,
    ) -> None:
        super().__init__(
            name=name,
            capabilities=ProviderCapabilities(predict=False),
            is_local=True,
            description="JEPA WMS provider scaffold.",
            package="worldforge",
            implementation_status="scaffold",
            deterministic=False,
            requires_credentials=False,
            required_env_vars=[JEPA_WMS_ENV_VAR],
            supported_modalities=[],
            artifact_types=[],
            notes=[
                "Generated scaffold; do not register as a real provider until implemented.",
                "Taxonomy category: JEPA latent predictive world model.",
                "Planned capabilities: score.",
            ],
            event_handler=event_handler,
        )

    def configured(self) -> bool:
        return bool(os.environ.get(JEPA_WMS_ENV_VAR))

    def health(self) -> ProviderHealth:
        started = perf_counter()
        if not self.configured():
            return ProviderHealth(
                name=self.name,
                healthy=False,
                latency_ms=max(0.1, (perf_counter() - started) * 1000),
                details=f"missing {JEPA_WMS_ENV_VAR}",
            )
        return ProviderHealth(
            name=self.name,
            healthy=False,
            latency_ms=max(0.1, (perf_counter() - started) * 1000),
            details="scaffold generated; no runtime adapter implemented",
        )

    def score_actions(self, *, info: JSONDict, action_candidates: object) -> ActionScoreResult:
        raise ProviderError(
            f"Provider '{self.name}' score_actions() scaffold is not implemented yet."
        )
