"""WorldForge: integration layer for physical-AI world-model workflows."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from worldforge.benchmark import (
    BenchmarkInputs,
    BenchmarkReport,
    BenchmarkResult,
    ProviderBenchmarkHarness,
    run_benchmark,
)
from worldforge.capabilities import (
    Cost,
    Embedder,
    Generator,
    Planner,
    Policy,
    Predictor,
    Reasoner,
    RunnableModel,
    Transferer,
)
from worldforge.evaluation import (
    EvalReport,
    EvalResult,
    EvalScenario,
    EvalSuite,
    EvaluationReport,
    EvaluationResult,
    EvaluationScenario,
    EvaluationSuite,
    GenerationEval,
    GenerationEvaluationSuite,
    PhysicsEval,
    PhysicsEvaluationSuite,
    PlanningEval,
    PlanningEvaluationSuite,
    ProviderSummary,
    ReasoningEval,
    ReasoningEvaluationSuite,
    TransferEval,
    TransferEvaluationSuite,
)
from worldforge.framework import (
    Comparison,
    Plan,
    PlanExecution,
    Prediction,
    World,
    WorldForge,
    list_eval_suites,
    run_eval,
)
from worldforge.models import (
    CAPABILITY_NAMES,
    Action,
    ActionPolicyResult,
    ActionScoreResult,
    BBox,
    DoctorReport,
    EmbeddingResult,
    GenerationOptions,
    Pose,
    Position,
    ProviderCapabilities,
    ProviderDoctorStatus,
    ProviderEvent,
    ProviderHealth,
    ProviderInfo,
    ProviderProfile,
    ProviderRequestPolicy,
    ReasoningResult,
    RequestOperationPolicy,
    RetryPolicy,
    Rotation,
    SceneObject,
    SceneObjectPatch,
    StructuredGoal,
    VideoClip,
    WorldForgeError,
    WorldStateError,
)

try:
    __version__ = version("worldforge-ai")
except PackageNotFoundError:  # pragma: no cover - fallback for editable local imports
    __version__ = "0.0.0"

__all__ = [
    "CAPABILITY_NAMES",
    "Action",
    "ActionPolicyResult",
    "ActionScoreResult",
    "BBox",
    "BenchmarkInputs",
    "BenchmarkReport",
    "BenchmarkResult",
    "Comparison",
    "Cost",
    "DoctorReport",
    "Embedder",
    "EmbeddingResult",
    "EvalReport",
    "EvalResult",
    "EvalScenario",
    "EvalSuite",
    "EvaluationReport",
    "EvaluationResult",
    "EvaluationScenario",
    "EvaluationSuite",
    "GenerationEval",
    "GenerationEvaluationSuite",
    "GenerationOptions",
    "Generator",
    "PhysicsEval",
    "PhysicsEvaluationSuite",
    "Plan",
    "PlanExecution",
    "Planner",
    "PlanningEval",
    "PlanningEvaluationSuite",
    "Policy",
    "Pose",
    "Position",
    "Prediction",
    "Predictor",
    "ProviderBenchmarkHarness",
    "ProviderCapabilities",
    "ProviderDoctorStatus",
    "ProviderEvent",
    "ProviderHealth",
    "ProviderInfo",
    "ProviderProfile",
    "ProviderRequestPolicy",
    "ProviderSummary",
    "Reasoner",
    "ReasoningEval",
    "ReasoningEvaluationSuite",
    "ReasoningResult",
    "RequestOperationPolicy",
    "RetryPolicy",
    "Rotation",
    "RunnableModel",
    "SceneObject",
    "SceneObjectPatch",
    "StructuredGoal",
    "TransferEval",
    "TransferEvaluationSuite",
    "Transferer",
    "VideoClip",
    "World",
    "WorldForge",
    "WorldForgeError",
    "WorldStateError",
    "__version__",
    "list_eval_suites",
    "run_benchmark",
    "run_eval",
]
