"""WorldForge: testable world-model workflows for physical-AI systems.

WorldForge is a Python integration layer that gives world-model providers, score models,
embodied policies, and media generators explicit capability contracts. Planning, evaluation,
benchmarks, diagnostics, local state, and CLI tooling are built on top of those contracts.

The package exposes the public surface used by adapters, CLI commands, evaluations, and
benchmarks. Public re-exports are loaded lazily so lightweight integrations, such as pytest
plugin discovery, do not import the full runtime stack before they need it.
"""

from __future__ import annotations

from importlib import import_module
from importlib.metadata import PackageNotFoundError, version
from typing import Any

try:
    __version__ = version("worldforge-ai")
except PackageNotFoundError:  # pragma: no cover - fallback for editable local imports
    __version__ = "0.0.0"

_EXPORTS: dict[str, str] = {  # pragma: no cover - initialized before pytest-cov by plugins
    "ActionCandidatePlan": "worldforge.action_candidates",
    "ActionCandidatePlans": "worldforge.action_candidates",
    "action_candidates_to_score_payload": "worldforge.action_candidates",
    "bounded_move_grid_candidates": "worldforge.action_candidates",
    "cartesian_offset_candidates": "worldforge.action_candidates",
    "normalize_action_candidates": "worldforge.action_candidates",
    "object_near_candidates": "worldforge.action_candidates",
    "swap_action_candidates": "worldforge.action_candidates",
    "BenchmarkBudget": "worldforge.benchmark",
    "BenchmarkGateReport": "worldforge.benchmark",
    "BenchmarkGateViolation": "worldforge.benchmark",
    "BenchmarkInputs": "worldforge.benchmark",
    "BenchmarkReport": "worldforge.benchmark",
    "BenchmarkResult": "worldforge.benchmark",
    "ProviderBenchmarkHarness": "worldforge.benchmark",
    "load_benchmark_budgets": "worldforge.benchmark",
    "load_benchmark_inputs": "worldforge.benchmark",
    "run_benchmark": "worldforge.benchmark",
    "Cost": "worldforge.capabilities",
    "Embedder": "worldforge.capabilities",
    "Generator": "worldforge.capabilities",
    "Planner": "worldforge.capabilities",
    "Policy": "worldforge.capabilities",
    "Predictor": "worldforge.capabilities",
    "Reasoner": "worldforge.capabilities",
    "RunnableModel": "worldforge.capabilities",
    "Transferer": "worldforge.capabilities",
    "CONFIG_PROFILE_OUTPUT_FORMATS": "worldforge.config_profiles",
    "CONFIG_PROFILE_RETRY_PRESETS": "worldforge.config_profiles",
    "CONFIG_PROFILE_SCHEMA_VERSION": "worldforge.config_profiles",
    "CONFIG_PROFILE_TIMEOUT_PRESETS": "worldforge.config_profiles",
    "ConfigProfile": "worldforge.config_profiles",
    "load_config_profile": "worldforge.config_profiles",
    "parse_config_profile": "worldforge.config_profiles",
    "validate_config_profile_provenance": "worldforge.config_profiles",
    "ReportRenderResult": "worldforge.report_renderers",
    "ReportRenderer": "worldforge.report_renderers",
    "get_report_renderer": "worldforge.report_renderers",
    "list_report_renderers": "worldforge.report_renderers",
    "register_report_renderer": "worldforge.report_renderers",
    "render_report_artifact": "worldforge.report_renderers",
    "EvalReport": "worldforge.evaluation",
    "EvalResult": "worldforge.evaluation",
    "EvalScenario": "worldforge.evaluation",
    "EvalSuite": "worldforge.evaluation",
    "EvaluationContext": "worldforge.evaluation",
    "EvaluationFailureCase": "worldforge.evaluation",
    "EvaluationFailureGallery": "worldforge.evaluation",
    "EvaluationReport": "worldforge.evaluation",
    "EvaluationResult": "worldforge.evaluation",
    "EvaluationScenario": "worldforge.evaluation",
    "EvaluationScenarioOutcome": "worldforge.evaluation",
    "EvaluationSuite": "worldforge.evaluation",
    "GenerationEval": "worldforge.evaluation",
    "GenerationEvaluationSuite": "worldforge.evaluation",
    "LIVE_SMOKE_EVIDENCE_SCHEMA_VERSION": "worldforge.live_smoke_evidence",
    "LIVE_SMOKE_EVIDENCE_STATUSES": "worldforge.live_smoke_evidence",
    "PhysicsEval": "worldforge.evaluation",
    "PhysicsEvaluationSuite": "worldforge.evaluation",
    "PlanningEval": "worldforge.evaluation",
    "PlanningEvaluationSuite": "worldforge.evaluation",
    "ProviderSummary": "worldforge.evaluation",
    "ReasoningEval": "worldforge.evaluation",
    "ReasoningEvaluationSuite": "worldforge.evaluation",
    "TransferEval": "worldforge.evaluation",
    "TransferEvaluationSuite": "worldforge.evaluation",
    "PROVIDER_CONTRACT_EVIDENCE_SCHEMA_VERSION": "worldforge.provider_contracts",
    "PROVIDER_CONTRACT_STATUSES": "worldforge.provider_contracts",
    "ProviderContractCheck": "worldforge.provider_contracts",
    "ProviderContractEvidence": "worldforge.provider_contracts",
    "provider_from_factory_path": "worldforge.provider_contracts",
    "run_provider_contract": "worldforge.provider_contracts",
    "Comparison": "worldforge.framework",
    "Plan": "worldforge.framework",
    "PlanExecution": "worldforge.framework",
    "Prediction": "worldforge.framework",
    "World": "worldforge.framework",
    "WorldForge": "worldforge.framework",
    "list_eval_suites": "worldforge.framework",
    "run_eval": "worldforge.framework",
    "ProviderBudgetExceededError": "worldforge.providers",
    "EmbodimentActionTranslator": "worldforge.providers",
    "EmbodimentTranslatorContract": "worldforge.providers",
    "ENTRY_POINT_DISABLE_ENV_VAR": "worldforge.providers",
    "ENTRY_POINT_GROUP": "worldforge.providers",
    "EntryPointDiscoveryReport": "worldforge.providers",
    "EntryPointSkip": "worldforge.providers",
    "discover_entry_point_providers": "worldforge.providers",
    "CAPABILITY_NEGOTIATION_SCHEMA_VERSION": "worldforge.capability_negotiation",
    "CapabilityNegotiationReport": "worldforge.capability_negotiation",
    "CapabilityProviderStatus": "worldforge.capability_negotiation",
    "CapabilityRequirement": "worldforge.capability_negotiation",
    "WorkflowNegotiation": "worldforge.capability_negotiation",
    "WorkflowSpec": "worldforge.capability_negotiation",
    "get_workflow": "worldforge.capability_negotiation",
    "list_workflow_names": "worldforge.capability_negotiation",
    "list_workflows": "worldforge.capability_negotiation",
    "negotiate_capabilities": "worldforge.capability_negotiation",
    "PruneCandidate": "worldforge.runs_prune",
    "PruneReport": "worldforge.runs_prune",
    "RUNS_PRUNE_SCHEMA_VERSION": "worldforge.runs_prune",
    "RunsRetentionPolicy": "worldforge.runs_prune",
    "apply_prune": "worldforge.runs_prune",
    "parse_runs_retention": "worldforge.runs_prune",
    "plan_prune": "worldforge.runs_prune",
    "ROUTING_ATTEMPT_STATUSES": "worldforge.provider_routing",
    "ProviderRoutingPolicy": "worldforge.provider_routing",
    "RoutingAttempt": "worldforge.provider_routing",
    "RoutingResult": "worldforge.provider_routing",
    "route_capability": "worldforge.provider_routing",
    "RUNTIME_ASSET_MANIFEST_SCHEMA_VERSION": "worldforge.providers",
    "RuntimeAssetManifest": "worldforge.providers",
    "validate_runtime_asset_manifest": "worldforge.providers",
    "HTML_REPORT_SCHEMA_VERSION": "worldforge.html_report",
    "render_benchmark_html": "worldforge.html_report",
    "render_comparison_html": "worldforge.html_report",
    "render_evaluation_html": "worldforge.html_report",
    "render_evidence_bundle_html": "worldforge.html_report",
    "render_issue_bundle_html": "worldforge.html_report",
    "OBJECT_CHANGE_KINDS": "worldforge.world_diff",
    "ObjectChange": "worldforge.world_diff",
    "WORLD_DIFF_SCHEMA_VERSION": "worldforge.world_diff",
    "WORLD_FIELD_NAMES": "worldforge.world_diff",
    "WorldDiff": "worldforge.world_diff",
    "WorldFieldChange": "worldforge.world_diff",
    "WorldPatch": "worldforge.world_diff",
    "apply_patch": "worldforge.world_diff",
    "diff_worlds": "worldforge.world_diff",
    "diff_worlds_from_paths": "worldforge.world_diff",
    "WORLD_MIGRATION_PREVIEW_SCHEMA_VERSION": "worldforge.world_migration_preview",
    "preview_world_migration": "worldforge.world_migration_preview",
    "preview_world_migration_from_path": "worldforge.world_migration_preview",
    "preview_world_migration_from_world_id": "worldforge.world_migration_preview",
    "render_world_migration_preview_markdown": "worldforge.world_migration_preview",
    "WORKFLOW_TRACE_SCHEMA_VERSION": "worldforge.workflow_trace",
    "WORKFLOW_TRACE_STEP_STATUSES": "worldforge.workflow_trace",
    "WorkflowArtifactRef": "worldforge.workflow_trace",
    "WorkflowTrace": "worldforge.workflow_trace",
    "WorkflowTraceStep": "worldforge.workflow_trace",
    "workflow_trace_from_provider_events": "worldforge.workflow_trace",
    "DATASET_MANIFEST_ENTRY_KINDS": "worldforge.dataset_manifests",
    "DATASET_MANIFEST_PRIVACY_CLASSIFICATIONS": "worldforge.dataset_manifests",
    "DATASET_MANIFEST_SCHEMA_VERSION": "worldforge.dataset_manifests",
    "DatasetManifest": "worldforge.dataset_manifests",
    "DatasetManifestEntry": "worldforge.dataset_manifests",
    "dataset_manifest_reference": "worldforge.dataset_manifests",
    "dataset_manifest_references": "worldforge.dataset_manifests",
    "load_dataset_manifest": "worldforge.dataset_manifests",
    "parse_dataset_manifest": "worldforge.dataset_manifests",
    "SCENARIO_ACTION_KINDS": "worldforge.scenarios",
    "SCENARIO_MATRIX_MAX_CASES": "worldforge.scenarios",
    "SCENARIO_SCHEMA_VERSION": "worldforge.scenarios",
    "Scenario": "worldforge.scenarios",
    "ScenarioAction": "worldforge.scenarios",
    "ScenarioExpectationCheck": "worldforge.scenarios",
    "ScenarioExpectedArtifact": "worldforge.scenarios",
    "ScenarioMatrix": "worldforge.scenarios",
    "ScenarioMatrixCase": "worldforge.scenarios",
    "ScenarioMatrixCaseResult": "worldforge.scenarios",
    "ScenarioMatrixResult": "worldforge.scenarios",
    "ScenarioObjectSpec": "worldforge.scenarios",
    "ScenarioResult": "worldforge.scenarios",
    "load_scenario": "worldforge.scenarios",
    "load_scenario_matrix": "worldforge.scenarios",
    "parse_scenario": "worldforge.scenarios",
    "parse_scenario_matrix": "worldforge.scenarios",
    "run_scenario": "worldforge.scenarios",
    "run_scenario_matrix": "worldforge.scenarios",
    "CAPABILITY_NAMES": "worldforge.models",
    "Action": "worldforge.models",
    "ActionPolicyResult": "worldforge.models",
    "ActionScoreResult": "worldforge.models",
    "BBox": "worldforge.models",
    "DoctorReport": "worldforge.models",
    "EmbeddingResult": "worldforge.models",
    "GenerationOptions": "worldforge.models",
    "Pose": "worldforge.models",
    "Position": "worldforge.models",
    "ProviderCapabilities": "worldforge.models",
    "ProviderDoctorStatus": "worldforge.models",
    "ProviderEvent": "worldforge.models",
    "ProviderHealth": "worldforge.models",
    "ProviderInfo": "worldforge.models",
    "ProviderLifecycleResult": "worldforge.models",
    "ProviderLifecycleStatus": "worldforge.models",
    "ProviderProfile": "worldforge.models",
    "ProviderRequestPolicy": "worldforge.models",
    "ReasoningResult": "worldforge.models",
    "RequestOperationPolicy": "worldforge.models",
    "RerunArtifactLogger": "worldforge.rerun",
    "RerunEventSink": "worldforge.rerun",
    "RerunRecordingConfig": "worldforge.rerun",
    "RerunSession": "worldforge.rerun",
    "RetryPolicy": "worldforge.models",
    "Rotation": "worldforge.models",
    "SCENE_ARTIFACT_KIND": "worldforge.scene_artifacts",
    "SCENE_ARTIFACT_MAX_METADATA_BYTES": "worldforge.scene_artifacts",
    "SCENE_ARTIFACT_SCHEMA_VERSION": "worldforge.scene_artifacts",
    "SceneObject": "worldforge.models",
    "SceneObjectPatch": "worldforge.models",
    "StructuredGoal": "worldforge.models",
    "VideoClip": "worldforge.models",
    "WorldForgeError": "worldforge.models",
    "WorldStateError": "worldforge.models",
    "create_rerun_event_handler": "worldforge.rerun",
    "render_live_smoke_registry_table": "worldforge.live_smoke_evidence",
    "validate_scene_artifact": "worldforge.scene_artifacts",
    "validate_live_smoke_entry": "worldforge.live_smoke_evidence",
    "validate_live_smoke_registry": "worldforge.live_smoke_evidence",
}

__all__ = sorted((*_EXPORTS, "__version__"))


def __getattr__(name: str) -> Any:
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(_EXPORTS[name])
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:  # pragma: no cover - module dir support
    return sorted((*globals(), *_EXPORTS))
