"""Render generated files for provider scaffold packs."""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent

from worldforge.provider_scaffold_models import CAPABILITIES, ProviderNames, ScaffoldOptions
from worldforge.provider_scaffold_templates import (
    CAPABILITY_MODEL_IMPORTS as _CAPABILITY_MODEL_IMPORTS,
)
from worldforge.provider_scaffold_templates import (
    CAPABILITY_STUB_TEMPLATES as _CAPABILITY_STUB_TEMPLATES,
)
from worldforge.provider_scaffold_templates import (
    CAPABILITY_TEST_TEMPLATES as _CAPABILITY_TEST_TEMPLATES,
)
from worldforge.provider_scaffold_templates import CapabilityTestTemplate as _CapabilityTestTemplate


def scaffold_files(options: ScaffoldOptions) -> dict[Path, str]:
    names = options.names
    return {
        options.root / "src" / "worldforge" / "providers" / f"{names.snake}.py": _provider_source(
            options
        ),
        options.root / "tests" / f"test_{names.snake}_provider.py": _test_source(options),
        options.root / "tests" / "fixtures" / "providers" / f"{names.snake}_success.json": (
            _fixture_payload(options, success=True)
        ),
        options.root / "tests" / "fixtures" / "providers" / f"{names.snake}_error.json": (
            _fixture_payload(options, success=False)
        ),
        options.root
        / "src"
        / "worldforge"
        / "providers"
        / "runtime_manifests"
        / f"{names.slug}.json.stub": _runtime_manifest_stub_source(options),
        options.root / "docs" / "src" / "providers" / f"{names.slug}.md": _docs_source(options),
        options.root / "docs" / "src" / "providers" / f"{names.slug}-workbench.md": (
            _workbench_checklist_source(options)
        ),
    }


def _provider_source(options: ScaffoldOptions) -> str:
    sections = (
        _provider_header_lines(options.names),
        _provider_import_lines(options),
        _provider_env_lines(options),
        _provider_class_lines(options),
        _provider_configured_lines(options),
        _provider_health_lines(options),
        [_capability_stubs(options.names, options.planned_capabilities)],
    )
    return "\n".join(line for section in sections for line in section).rstrip() + "\n"


def _provider_header_lines(names: ProviderNames) -> list[str]:
    return [
        f'"""Provider scaffold for {names.display}.',
        "",
        "Generated by ``scripts/scaffold_provider.py``. Keep public capabilities disabled until",
        "the TODO methods return validated WorldForge models and have fixture-driven tests.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]


def _provider_import_lines(options: ScaffoldOptions) -> list[str]:
    lines: list[str] = []
    if options.env_var:
        lines.append("import os")
    lines.extend(
        [
            "from collections.abc import Callable",
            "from time import perf_counter",
            "",
            "from worldforge.models import (",
        ]
    )
    lines.extend(f"    {import_name}," for import_name in _provider_model_imports(options))
    lines.extend(
        [
            ")",
            "",
            f"from .base import {', '.join(_provider_base_imports(options))}",
            "",
        ]
    )
    return lines


def _provider_model_imports(options: ScaffoldOptions) -> list[str]:
    imports = ["ProviderCapabilities", "ProviderEvent", "ProviderHealth"]
    for capability in options.planned_capabilities:
        imports.extend(_CAPABILITY_MODEL_IMPORTS.get(capability, ()))
    return sorted(dict.fromkeys(imports))


def _provider_base_imports(options: ScaffoldOptions) -> list[str]:
    imports = ["BaseProvider", "ProviderError", "ProviderProfileSpec"]
    if "predict" in options.planned_capabilities:
        imports.insert(1, "PredictionPayload")
    return imports


def _provider_env_lines(options: ScaffoldOptions) -> list[str]:
    if options.env_var is None:
        return []
    env_constant = f"{options.names.snake.upper()}_ENV_VAR"
    return [f'{env_constant} = "{options.env_var}"', "", ""]


def _provider_class_lines(options: ScaffoldOptions) -> list[str]:
    names = options.names
    planned = ", ".join(options.planned_capabilities)
    taxonomy_note = f"Taxonomy category: {options.taxonomy}."
    planned_note = f"Planned capabilities: {planned}."
    return [
        f"class {names.class_name}(BaseProvider):",
        f'    """Generated scaffold for the {names.display} provider.',
        "",
        "    Planned capabilities are intentionally not advertised yet. Enable them",
        "    only after the corresponding methods call the real upstream runtime",
        "    and return validated public models.",
        '    """',
        "",
        f"    planned_capabilities = {options.planned_capabilities!r}",
        f"    taxonomy_category = {options.taxonomy!r}",
        f"    scaffold_implementation_status = {options.implementation_status!r}",
        "",
        "    def __init__(",
        "        self,",
        f'        name: str = "{names.slug}",',
        "        *,",
        "        event_handler: Callable[[ProviderEvent], None] | None = None,",
        "    ) -> None:",
        "        super().__init__(",
        "            name=name,",
        "            capabilities=ProviderCapabilities(predict=False),",
        "            profile=ProviderProfileSpec(",
        f"                is_local={options.is_local!r},",
        f'                description="{names.display} provider scaffold.",',
        '                package="worldforge",',
        f"                implementation_status={options.implementation_status!r},",
        "                deterministic=False,",
        f"                requires_credentials={not options.is_local!r},",
        f"                required_env_vars={_provider_required_env_vars(options)},",
        "                supported_modalities=(),",
        "                artifact_types=(),",
        "                notes=(",
        '                    "Generated scaffold; do not register as a real provider until '
        'implemented.",',
        f"                    {taxonomy_note!r},",
        f"                    {planned_note!r},",
        "                ),",
        "            ),",
        "            event_handler=event_handler,",
        "        )",
        "",
    ]


def _provider_required_env_vars(options: ScaffoldOptions) -> str:
    if options.env_var is None:
        return "()"
    return f"({options.names.snake.upper()}_ENV_VAR,)"


def _provider_configured_lines(options: ScaffoldOptions) -> list[str]:
    lines = ["    def configured(self) -> bool:"]
    if options.env_var:
        lines.append(f"        return bool(os.environ.get({options.names.snake.upper()}_ENV_VAR))")
    else:
        lines.append("        return True")
    return [*lines, ""]


def _provider_health_lines(options: ScaffoldOptions) -> list[str]:
    lines = [
        "    def health(self) -> ProviderHealth:",
        "        started = perf_counter()",
    ]
    if options.env_var:
        lines.extend(_provider_missing_config_health_lines(options.names))
    lines.extend(
        [
            "        return ProviderHealth(",
            "            name=self.name,",
            "            healthy=False,",
            "            latency_ms=max(0.1, (perf_counter() - started) * 1000),",
            '            details="scaffold generated; no runtime adapter implemented",',
            "        )",
            "",
        ]
    )
    return lines


def _provider_missing_config_health_lines(names: ProviderNames) -> list[str]:
    env_constant = f"{names.snake.upper()}_ENV_VAR"
    return [
        "        if not self.configured():",
        "            return ProviderHealth(",
        "                name=self.name,",
        "                healthy=False,",
        "                latency_ms=max(0.1, (perf_counter() - started) * 1000),",
        f'                details=f"missing {{{env_constant}}}",',
        "            )",
    ]


def _capability_stubs(names: ProviderNames, planned_capabilities: tuple[str, ...]) -> str:
    planned = set(planned_capabilities)
    stubs = [
        template.source.strip("\n")
        for template in _CAPABILITY_STUB_TEMPLATES
        if template.capability in planned
    ]
    if not stubs:
        raise ValueError(f"{names.slug} scaffold requires at least one planned capability")
    return "\n\n".join(stubs)


def _test_source(options: ScaffoldOptions) -> str:
    sections = [
        _provider_test_imports(options.names),
        _profile_scaffold_test(options),
        _capability_calls_fail_closed_test(options.names),
        *_optional_provider_test_sections(options),
    ]
    return "\n\n".join(section.rstrip() for section in sections) + "\n"


def _provider_test_imports(names: ProviderNames) -> str:
    return "\n".join(
        [
            "from __future__ import annotations",
            "",
            "import pytest",
            "",
            "from worldforge import Action",
            f"from worldforge.providers.{names.snake} import {names.class_name}",
            "from worldforge.providers.base import ProviderError",
        ]
    )


def _profile_scaffold_test(options: ScaffoldOptions) -> str:
    names = options.names
    capability_rows = [f'            "{capability}",' for capability in CAPABILITIES]
    return "\n".join(
        [
            f"def test_{names.snake}_profile_starts_as_safe_scaffold() -> None:",
            f"    provider = {names.class_name}()",
            "    profile = provider.profile()",
            "",
            f'    assert profile.name == "{names.slug}"',
            f"    assert profile.implementation_status == {options.implementation_status!r}",
            "    assert profile.supported_tasks == []",
            "    assert all(",
            "        profile.capabilities.supports(capability) is False",
            "        for capability in (",
            *capability_rows,
            "        )",
            "    )",
            f"    assert provider.planned_capabilities == {options.planned_capabilities!r}",
            f"    assert provider.taxonomy_category == {options.taxonomy!r}",
            "    assert (",
            f"        provider.scaffold_implementation_status == {options.implementation_status!r}",
            "    )",
            '    assert any("do not register" in note for note in profile.notes)',
        ]
    )


def _capability_calls_fail_closed_test(names: ProviderNames) -> str:
    return "\n".join(
        [
            f"def test_{names.snake}_capability_calls_fail_closed_until_promoted() -> None:",
            f"    provider = {names.class_name}()",
            "    calls = {",
            '        "predict": lambda: provider.predict({}, Action.noop(), 1),',
            '        "embed": lambda: provider.embed(text="query"),',
            '        "score": lambda: provider.score_actions(info={}, action_candidates=[]),',
            '        "policy": lambda: provider.select_actions(info={}),',
            "    }",
            "",
            "    for capability, call in calls.items():",
            "        assert provider.profile().capabilities.supports(capability) is False",
            '        with pytest.raises(ProviderError, match="not implement"):',
            "            call()",
        ]
    )


def _optional_provider_test_sections(options: ScaffoldOptions) -> list[str]:
    sections = _missing_configuration_test_sections(options)
    sections.extend(_planned_capability_test_sections(options))
    return sections


def _missing_configuration_test_sections(options: ScaffoldOptions) -> list[str]:
    if options.env_var is None:
        return []
    names = options.names
    test_name = f"test_{names.snake}_health_reports_missing_configuration"
    return [
        "\n".join(
            [
                f"def {test_name}(monkeypatch) -> None:",
                f'    monkeypatch.delenv("{options.env_var}", raising=False)',
                "",
                f"    health = {names.class_name}().health()",
                "",
                "    assert health.healthy is False",
                f'    assert "{options.env_var}" in health.details',
            ]
        )
    ]


def _planned_capability_test_sections(options: ScaffoldOptions) -> list[str]:
    planned = set(options.planned_capabilities)
    return [
        _capability_not_implemented_test(options.names, template)
        for template in _CAPABILITY_TEST_TEMPLATES
        if template.capability in planned
    ]


def _capability_not_implemented_test(
    names: ProviderNames,
    template: _CapabilityTestTemplate,
) -> str:
    return "\n".join(
        [
            f"def test_{names.snake}_{template.function_suffix}_is_not_implemented_yet() -> None:",
            f"    provider = {names.class_name}()",
            *template.setup_lines,
            '    with pytest.raises(ProviderError, match="not implemented"):',
            *template.call_lines,
        ]
    )


def _docs_source(options: ScaffoldOptions) -> str:
    sections = (
        _docs_intro_section(options),
        _docs_planned_capabilities_section(options),
        _docs_generated_files_section(options),
        _docs_configuration_section(options),
        _docs_runtime_manifest_section(options),
        _docs_contract_section(),
        _docs_tests_section(),
        _docs_release_checklist_section(options),
    )
    return "\n\n".join(sections) + "\n"


def _docs_intro_section(options: ScaffoldOptions) -> str:
    names = options.names
    return dedent(
        f"""\
        # {names.display} Provider

        Status: {options.implementation_status}

        Taxonomy category: {options.taxonomy}

        This file was generated by `scripts/scaffold_provider.py`. Treat it as a checklist, not as
        proof that the provider is implemented.

        The generated provider is not executable until the promotion criteria pass: every planned
        capability must call a real runtime, return validated WorldForge models, have
        fixture-backed parser and failure tests, and advertise only the capabilities implemented
        end to end.
        """
    ).strip()


def _docs_planned_capabilities_section(options: ScaffoldOptions) -> str:
    rows = "\n".join(
        f"- [ ] `{capability}` implemented, advertised, and tested"
        for capability in options.planned_capabilities
    )
    return f"## Planned Capabilities\n\n{rows}"


def _docs_generated_files_section(options: ScaffoldOptions) -> str:
    names = options.names
    return dedent(
        f"""\
        ## Generated Contract Files

        - Provider scaffold: `src/worldforge/providers/{names.snake}.py`
        - Contract tests: `tests/test_{names.snake}_provider.py`
        - Placeholder fixtures: `tests/fixtures/providers/{names.snake}_success.json` and
          `tests/fixtures/providers/{names.snake}_error.json`
        - Runtime manifest stub:
          `src/worldforge/providers/runtime_manifests/{names.slug}.json.stub`
        - Workbench checklist: `docs/src/providers/{names.slug}-workbench.md`
        """
    ).strip()


def _docs_configuration_section(options: ScaffoldOptions) -> str:
    return "\n".join(
        [
            "## Configuration",
            "",
            _docs_required_env_line(options),
            (
                "- Optional dependencies: document runtime packages, model checkpoints, and "
                "cache paths."
            ),
            (
                "- Registration rule: document the environment variables required before "
                "auto-registration."
            ),
        ]
    )


def _docs_required_env_line(options: ScaffoldOptions) -> str:
    if options.env_var is None:
        return "- Required environment variable: none yet."
    return f"- Required environment variable: `{options.env_var}`."


def _docs_runtime_manifest_section(options: ScaffoldOptions) -> str:
    names = options.names
    return dedent(
        f"""\
        ## Runtime Manifest Stub

        The generated `.json.stub` file is intentionally incomplete and must not be renamed to
        `{names.slug}.json` or treated as smoke evidence until every TODO is replaced with a real
        host-owned runtime contract and `uv run pytest tests/test_provider_runtime_manifests.py`
        passes.
        """
    ).strip()


def _docs_contract_section() -> str:
    return dedent(
        """\
        ## Contract To Define

        - Input shape, range, and semantic constraints.
        - Output schema and score direction, if applicable.
        - Provider-specific limits such as duration, resolution, action tensor shape, file size,
          content type, timeout, retry, and polling behavior.
        - Failure modes for malformed upstream payloads, partial task output, expired artifacts,
          unsupported content types, missing credentials, and unavailable local checkpoints.
        """
    ).strip()


def _docs_tests_section() -> str:
    return dedent(
        """\
        ## Tests To Add

        - Fixture-driven happy path.
        - Malformed upstream payload.
        - Provider-specific input limit.
        - Event emission for success and failure.
        - Contract test with `worldforge.testing.assert_provider_contract(...)` when the provider
          advertises public capabilities.
        """
    ).strip()


def _docs_release_checklist_section(options: ScaffoldOptions) -> str:
    names = options.names
    return dedent(
        f"""\
        ## Release Checklist

        - [ ] Provider capabilities are narrow and truthful.
        - [ ] Provider profile metadata is complete.
        - [ ] Runtime manifest stub is complete, renamed, and validated or intentionally omitted.
        - [ ] `uv run worldforge provider workbench {names.slug} --format markdown` has no failed
              checks after a catalog entry or direct workbench target exists.
        - [ ] Public API docs mention new failure modes.
        - [ ] `docs/src/providers/README.md` links this provider page.
        - [ ] `AGENTS.md` documents any new commands, dependencies, or gotchas.
        - [ ] `CHANGELOG.md` records the user-visible behavior.
        """
    )


def _fixture_payload(options: ScaffoldOptions, *, success: bool) -> str:
    payload = {
        "provider": options.names.slug,
        "fixture_status": "placeholder",
        "implementation_status": options.implementation_status,
        "taxonomy_category": options.taxonomy,
        "planned_capabilities": list(options.planned_capabilities),
        "replace_before_promotion": True,
        "usable_as_evidence": False,
    }
    if success:
        payload["status"] = "replace-with-real-success-payload"
    else:
        payload["error"] = {
            "type": "replace-with-real-provider-error",
            "message": "Replace this scaffold fixture with a real malformed upstream response.",
        }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _runtime_manifest_stub_source(options: ScaffoldOptions) -> str:
    names = options.names
    required_env_vars = [options.env_var] if options.env_var is not None else ["TODO_RUNTIME_ENV"]
    payload = {
        "_instructions": (
            f"Incomplete scaffold stub for {names.slug}. Replace every TODO, remove "
            "stub_status/usable_as_evidence, rename this file to "
            f"{names.slug}.json, and validate it before using it as runtime evidence."
        ),
        "schema_version": 1,
        "provider": names.slug,
        "implementation_status": options.implementation_status,
        "stub_status": "incomplete",
        "usable_as_evidence": False,
        "capabilities": list(options.planned_capabilities),
        "optional_dependencies": ["TODO_RUNTIME_PACKAGE"],
        "required_env_vars": required_env_vars,
        "optional_env_vars": [],
        "default_model": "TODO_MODEL_OR_RUNTIME_ALIAS",
        "device_support": ["TODO_DEVICE"],
        "host_owned_artifacts": ["TODO_HOST_OWNED_CHECKPOINT_OR_RUNTIME_ARTIFACT"],
        "minimum_smoke_command": (
            "TODO uv run worldforge-smoke-"
            f"{names.slug} --run-manifest .worldforge/runs/{names.slug}-live/run_manifest.json"
        ),
        "expected_success_signal": (
            "TODO describe the validated provider result and sanitized run_manifest.json signal"
        ),
        "setup_hint": "TODO document host-owned install, credentials, cache, and checkpoint setup",
        "docs_path": f"docs/src/providers/{names.slug}.md",
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _workbench_checklist_source(options: ScaffoldOptions) -> str:
    names = options.names
    planned = ", ".join(f"`{capability}`" for capability in options.planned_capabilities)
    return dedent(
        f"""\
        # {names.display} Provider Workbench Checklist

        Status: {options.implementation_status}

        This checklist was generated by `scripts/scaffold_provider.py`. It is not evidence by
        itself; it names the contract work required before `{names.slug}` becomes executable.

        ## Scaffold Surface

        - Planned capabilities: {planned}
        - Provider source: `src/worldforge/providers/{names.snake}.py`
        - Provider docs: `docs/src/providers/{names.slug}.md`
        - Placeholder fixtures: `tests/fixtures/providers/{names.snake}_*.json`
        - Runtime manifest stub:
          `src/worldforge/providers/runtime_manifests/{names.slug}.json.stub`

        ## Fail-Closed Checks

        - [ ] Generated provider profile reports
              `implementation_status="{options.implementation_status}"`.
        - [ ] Generated provider advertises no public capabilities before promotion.
        - [ ] Every generated capability call raises `ProviderError` until real runtime behavior
              is implemented.
        - [ ] Existing files are not overwritten unless `--force` is explicit.

        ## Promotion Work

        - [ ] Replace placeholder fixtures with real success and malformed upstream payloads.
        - [ ] Replace generated method stubs with real runtime calls and typed WorldForge models.
        - [ ] Validate provider events do not expose secrets, signed URLs, raw tensors, or local
              checkpoint paths.
        - [ ] Replace every runtime manifest TODO, rename `.json.stub` to `.json`, and run
              `uv run pytest tests/test_provider_runtime_manifests.py`.
        - [ ] Add catalog registration only after configuration, docs, fixtures, and runtime
              evidence are ready.

        ## Workbench Target

        Add a catalog entry or direct workbench target before running this command:

        ```bash
        uv run worldforge provider workbench {names.slug} --format markdown
        ```

        ## Validation Commands

        ```bash
        uv run pytest tests/test_{names.snake}_provider.py
        uv run python scripts/generate_provider_docs.py --check
        uv run pytest tests/test_provider_catalog_docs.py
        uv run mkdocs build --strict
        ```
        """
    )
